import { Flight, QuickPrompt } from '@/types';

export const QUICK_PROMPTS: QuickPrompt[] = [
  { emoji: '🌏', text: 'Quiero ir a Asia en agosto, clima cálido y naturaleza activa' },
  { emoji: '🏖️', text: 'Busco playa en el Caribe con presupuesto moderado' },
  { emoji: '💑', text: '¿Cuáles son los mejores destinos para luna de miel en Europa?' },
  { emoji: '⛷️', text: 'Me encanta el ski, ¿cuáles son los mejores resorts?' },
];

// ── MOCK FLIGHTS ─────────────────────────────────────────────────────────────
export const MOCK_FLIGHTS: Flight[] = [
  {
    flightNumber: 'LA2091',
    airline: 'LATAM Airlines',
    route: 'LIM-BRC',
    originAirport: 'Jorge Chávez',
    destinationAirport: 'San Carlos de Bariloche',
    departureTime: '2026-08-10T06:30:00',
    arrivalTime: '2026-08-10T16:45:00',
    durationMinutes: 555,
    stops: 1,
    nonstop: false,
    price: 498,
    currency: 'USD',
    cabinClass: 'economy',
    searchDate: '2026-08-10',
    trendEmoji: '📉',
    recommendation: 'Conviene comprar ahora',
    previousFare: 580,
    fareChanged: true,
    fareDifference: -82,
    percentageChange: -14.1,
  },
  {
    flightNumber: 'AR1082',
    airline: 'Aerolíneas Argentinas',
    route: 'LIM-BRC',
    originAirport: 'Jorge Chávez',
    destinationAirport: 'San Carlos de Bariloche',
    departureTime: '2026-08-10T10:00:00',
    arrivalTime: '2026-08-10T22:30:00',
    durationMinutes: 510,
    stops: 1,
    nonstop: false,
    price: 520,
    currency: 'USD',
    cabinClass: 'economy',
    searchDate: '2026-08-10',
    trendEmoji: '➖',
    recommendation: 'Precio estable',
  },
  {
    flightNumber: 'IB6830',
    airline: 'Iberia',
    route: 'LIM-MAD',
    originAirport: 'Jorge Chávez',
    destinationAirport: 'Adolfo Suárez Madrid-Barajas',
    departureTime: '2026-08-20T23:59:00',
    arrivalTime: '2026-08-21T18:30:00',
    durationMinutes: 750,
    stops: 0,
    nonstop: true,
    price: 780,
    currency: 'USD',
    cabinClass: 'economy',
    searchDate: '2026-08-20',
    trendEmoji: '📈',
    recommendation: 'El precio subió',
  },
  {
    flightNumber: 'LA540',
    airline: 'LATAM Airlines',
    route: 'LIM-SCL',
    originAirport: 'Jorge Chávez',
    destinationAirport: 'Arturo Merino Benítez',
    departureTime: '2026-08-08T07:00:00',
    arrivalTime: '2026-08-08T10:30:00',
    durationMinutes: 210,
    stops: 0,
    nonstop: true,
    price: 320,
    currency: 'USD',
    cabinClass: 'economy',
    searchDate: '2026-08-08',
    trendEmoji: '📉',
    recommendation: 'Precio bajo, ¡buen momento!',
    previousFare: 410,
    fareChanged: true,
    fareDifference: -90,
    percentageChange: -21.9,
  },
];

export const BOT_WELCOME_MESSAGE =
  '¡Hola! Soy **SAFAGO**, tu asesor de viajes con IA 🌍\n\n¿Tienes un destino en mente o prefieres que descubramos juntos el viaje perfecto para ti?';
